### ISSUE TITLE
Add delay updated markdown component for often updating text

### ISSUE THREAD

**Issue by hhyyrylainen** [StardustDL/RazorComponents.Markdown#71]
For my use case I want to use markdown both for already set text and also for a live preview of input. For that second case it would be excellent to have a way to say "wait a little bit" between text changes before running markdown rendering on it to a component. That way the live preview when editing text would be much less CPU intensive.

Not sure if the issue title is the best. And also feel free to close this if this is out of scope for this library, in that case I'll do my own light wrapper that controls how often text updates are passed through to markdown rendering.

**Comment by StardustDL** [comment]
I think it's interesting and useful but now I have no idea how to implement it properly. If you have ideas, PR is welcomed.

Also if you need a Markdown editor, maybe [Vditor](https://github.com/Vanessa219/vditor) is a possible choice. I also do a light wrapper in Blaozr for it, see [here](https://github.com/StardustDL/razorcomponents#vditors) and its [demo](https://github.com/StardustDL/razorcomponents/blob/b0962df42597a1b8803ae9c17ad30d64ffe3740c/test/Demo/Pages/VditorPage.razor). It's easy to use but maybe difficult to customize.

**Comment by hhyyrylainen** [comment]
Vditor seems a bit overkill for what I'm planning to use markdown for. I also have pretty bad experience with WYSIWYG style markdown editors, they always seem to break the layout, so I'd prefer a solution (maybe the split view mode of vditor would be good, but I didn't find a demo page where I could try that) that has pure markdown text input.

As for how I plan to implement this is basically to just hook into the on params set method, which starts a timer (if not running) and then that timer copies the markdown text into a private field which is then used to render the markdown. So basically I would throttle how often the markdown passed to this library can get updated.

**Comment by hhyyrylainen** [comment]
Finally got around to this, here's what I wrote (I don't have a working clientside debugger so I couldn't fully validate that markdown re-rendering with the old text doesn't accidentally happen):
```
@using System.Timers
@implements IDisposable

<MarkdownRenderer Value="@(activeText ?? string.Empty)" Style="@Style" Class="@Class" />

@code {
    private string activeText;

    private readonly Timer updateTimer = new(1000);

    [Parameter]
    public string Value { get; set; }

    [Parameter]
    public string Style { get; set; } = "";

    [Parameter]
    public string Class { get; set; } = "";

    [Parameter]
    public double UpdateInterval { get; set; } = 1000;

    public UpdateLimitedMarkdown()
    {
        updateTimer.Enabled = false;
        updateTimer.Elapsed += OnUpdateTimer;
    }

    public void Dispose()
    {
        updateTimer.Dispose();
    }

    protected override async Task OnParametersSetAsync()
    {
        updateTimer.Interval = UpdateInterval;
        await base.OnParametersSetAsync();

        if (Value == null)
        {
            activeText = null;
        } else if (activeText == null)
        {
            activeText = Value;
        }
        else
        {
            // Rate limited updating is used here
            updateTimer.Enabled = true;
        }
    }

    private async void OnUpdateTimer(object sender, ElapsedEventArgs e)
    {
        if (activeText == Value)
        {
            updateTimer.Enabled = false;
            return;
        }

        activeText = Value;
        await InvokeAsync(StateHasChanged);
    }
}
```

I've never worked on nuget packages so I don't know how I would add this and test this coming from a library properly.

**Comment by StardustDL** [comment]
Thank you for your example! I use `Task.Delay` to replace `Timer` in my implementation and integrate it into `MarkdownRenderer` component through `RenderInterval` parameter.

**Comment by hhyyrylainen** [comment]
Thanks, that looks pretty good. I'll give it a try once the nuget packages are updated.

**Comment by StardustDL** [comment]
The [package](https://www.nuget.org/packages/StardustDL.RazorComponents.Markdown/0.0.3.28) on NuGet has been updated.

**Comment by hhyyrylainen** [comment]
I forgot to test this out. I've now given this a go and it seems to work perfectly. Thanks for implementing this feature.
