### ISSUE TITLE
Is it possible to use the @css block?

### ISSUE THREAD

**Issue by DocBrown101** [StardustDL/RazorComponents.Markdown#9]
## In 1 file
 > Component.razor
 
 ```cs
 <h1>My Component/h1>
 
 @code{
 // code goes here
 }
 
 @css{
 // scoped css
 )
 ```
 
 ## In multi files
 * Component.razor
 * Component.razor.cs
 * Component.razor.css

**Comment by StardustDL** [comment]
I think it's not the features of this component. It depends on Blazor features, see this issue https://github.com/dotnet/aspnetcore/issues/10170 for details. If Blazor supports it, this component will support it too.
